osp/os1/urls.py
from django.conf.urls import url
from . import views

app_name='os1'

urlpatterns = [
    url(r'^help/$',views.help,name='help'),
    url(r'^index/$',views.index,name='index'),
]

osp/osp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from os1 import views

urlpatterns = [
url(r'^$',views.users,name='users'),
    url(r'^os1/',include('os1.urls')),
    path('admin/', admin.site.urls),
]

osp/os1/models.py
from django.db import models
# SuperUserInformation
# User: Jose
# Email: training@pieriandata.com
# Password: testpassword

# Create your models here.
class User(models.Model):
    rows=models.IntegerField()
    columns=models.IntegerField()
    max_allocation_matrix=models.CharField(max_length=128)
    allocation_matrix=models.CharField(max_length=128)
    available_vector=models.CharField(max_length=128)
    available_vector1=models.CharField(max_length=128)

osp/os1/forms.py
from django import forms
from os1.models import User

class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'

osp/os1/views.py
from django.shortcuts import render
from .forms import NewUserForm

def index(request):
    return render(request,'os1/index.html')

def help(request):
    helpdict = {'help_insert':'HELP PAGE'}
    return render(request,'os1/help.html',context=helpdict)

def users(request):
    form = NewUserForm()

    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR FORM INVALID')

    return render(request,'os1/users.html',{'form':form})

osp/templates/os1/help.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>HELP PAGE</title>
  </head>
  <body>
    {{ help_insert }}

  </body>
</html>

osp/templates/os1/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>Welcome!</h1>
        <h2>Go to /users to sign up!</h2>



      </div>
    </div>
    <form class="" action="mailto:prashant@gmail.com" method="post">
    <input type="submit" name="" value="submit">

    </form>
  </body>
</html>

osp/templates/os1/users.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Users</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <div class="container">
      <h1>Please sign up here!</h1>
      <form action= "{% url "os1:index" %}"  method="POST" >
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class='btn btn-primary' value="Submit">
      </form>
    </div>

  </body>
</html>